---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: install packages & Applications
      package:
        name:
          - htop
          - tmux
          - vim-nox
          - python3-psutil
          - wget
          - apt-transport-https
          - ca-certificates
          - gnupg-agent
          - curl
          - software-properties-common
          - filezilla
          - hardinfo
        state: present
        update_cache: yes

    # Install Applications
    - name: install application with snap
      snap:
        name:
          - postman
          - chromium
          - docker
        classic: yes

    # Install Visual Studio Code
    - name: install key MS (apt)
      become: yes
      apt_key:
        url: "https://packages.microsoft.com/keys/microsoft.asc"
        state: present

    - name: install VS Code repo (apt)
      become: yes
      apt_repository:
        repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
        filename: vscode
        state: present

    - name: Install VS Code (apt)
      become: yes
      apt:
        name: code
        state: latest
        update_cache: yes

    - name: Install extensions Visual Studio Code
      become: yes
      become_user: chmazur
      command: "code --install-extension {{item}}"
      loop:
        - ms-dotnettools.csharp
        - vscode-icons-team.vscode-icons
        - ms-mssql.mssql
        - ms-azuretools.vscode-docker
        - redhat.vscode-yaml
        - vscoss.vscode-ansible
        - ms-vscode.vscode-node-azure-pack
        - ms-azuretools.vscode-azureappservice
        - eamodio.gitlens
        - github.vscode-pull-request-github
        - golang.go
        - ms-vscode-remote.remote-ssh
        - msjsdiag.debugger-for-chrome
        - esbenp.prettier-vscode
        - dsznajder.es7-react-js-snippets
        - ecmel.vscode-html-css

  # Install dotnet 5
    - name: Download MS product repository
      get_url:
        url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
        dest: /tmp/packages-microsoft-prod.deb
    - name: Add the package repository
      become: yes
      command: "dpkg -i /tmp/packages-microsoft-prod.deb"        
    - name: Install MS product repository
      apt: deb=/tmp/packages-microsoft-prod.deb
      become: yes
    - name: Install .NET Core SDK
      apt:
        name: dotnet-sdk-5.0
        state: present
        update_cache: yes
      become: yes

    # Install Docker
    - name: Adding GPG
      become: yes
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adding repository Docker
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: copy .bashrc file
      copy:
        src: files/bashrc
        dest: /home/chmazur/.bashrc
        owner: chmazur
        group: chmazur
